import {
  HeartPulse, Siren, Pill, Baby, Scissors, ScanLine, Stethoscope, FlaskConical,
  Layers, Bone, Library, BookMarked, ListChecks, GraduationCap, BadgeCheck, Plane, Briefcase, FolderOpen,
  Star, SquareStack, ClipboardList, FolderUp, Handshake,
  type LucideIcon,
} from 'lucide-react';

// Same order used by the member-sync-library edge function's categorizer,
// so dashboard rows read in a sensible, stable sequence.
export const CATEGORY_ORDER = [
  'Cardiologia & ECG',
  'Emergência, PS & Trauma',
  'Prescrições & Plantão',
  'Pediatria',
  'Cirurgia & GO',
  'Radiologia & Imagem',
  'Semiologia & Clínica',
  'Farmacologia & Bioquímica',
  'Especialidades',
  'Anatomia & Ciclo Básico',
  'Livros & Apostilas',
  'Resumos, Cards & Mapas Mentais',
  'Banco de Questões & Simulados',
  'Extensivo & Intensivo · Residência',
  'Revalida',
  'Intercâmbio & Carreira Internacional',
  'Carreira, Gestão & Marketing',
  'Outros cursos',
];

export const CATEGORY_ICON: Record<string, LucideIcon> = {
  'Cardiologia & ECG': HeartPulse,
  'Emergência, PS & Trauma': Siren,
  'Prescrições & Plantão': Pill,
  'Pediatria': Baby,
  'Cirurgia & GO': Scissors,
  'Radiologia & Imagem': ScanLine,
  'Semiologia & Clínica': Stethoscope,
  'Farmacologia & Bioquímica': FlaskConical,
  'Especialidades': Layers,
  'Anatomia & Ciclo Básico': Bone,
  'Livros & Apostilas': Library,
  'Resumos, Cards & Mapas Mentais': BookMarked,
  'Banco de Questões & Simulados': ListChecks,
  'Extensivo & Intensivo · Residência': GraduationCap,
  'Revalida': BadgeCheck,
  'Intercâmbio & Carreira Internacional': Plane,
  'Carreira, Gestão & Marketing': Briefcase,
  'Outros cursos': FolderOpen,
  'Favoritos': Star,
  'Flashcards': SquareStack,
  'Banco de Questões': ClipboardList,
  'Acervo Público': FolderUp,
  'Programa de Afiliados': Handshake,
};
