// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { createSafeStorage } from '@/lib/safeStorage';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const FETCH_TIMEOUT_MS = 10000;
// Login/signup/token-refresh (/auth/v1/*) is the single most disruptive place
// for a fetch to fail early — a bit of extra latency there (slow mobile
// network, a cold GoTrue instance) shouldn't hard-abort a login that would've
// completed fine at 12-15s. Still bounded, just more generous than a normal
// data query.
const AUTH_TIMEOUT_MS = 25000;
// A few admin-triggered batch jobs legitimately run longer than a normal
// query (member-sync-library crawls large courses; run-email-campaign has
// its own 6-minute per-batch allowance; admin-backfill-lesson-durations reads
// real bytes from Drive per lesson — a batch of 8 measured at ~30s) — exempt
// them from the blanket timeout.
const TIMEOUT_EXEMPT = /\/functions\/v1\/(member-sync-library|run-email-campaign|admin-backfill-lesson-durations|admin-capi-health|admin-capi-backfill|generate-flashcards|generate-study-plan|member-assistant|archive-manage)/;
// member-auth-request/create-trial-access are the login/trial entry points —
// same reasoning as /auth/v1/ below, just implemented as our own Edge
// Functions instead of GoTrue's built-in endpoints.
const AUTH_PATH = /\/auth\/v1\/|\/functions\/v1\/(member-auth-request|create-trial-access)/;

// Criar cobrança tem que ter um orçamento MUITO maior que uma consulta comum.
// A chamada faz três idas e voltas antes de responder (sessão, gravar o
// pedido, criar a preferência no Mercado Pago) e ainda paga a partida a frio
// da Edge Function — em rede móvel isso passa de 10s com facilidade.
//
// Abortar aqui é pior do que esperar: o servidor conclui assim mesmo, então o
// aluno via "Failed to send a request to the Edge Function" enquanto o pedido
// e o checkout JÁ existiam do outro lado. Foi exatamente o que aconteceu na
// loja — todos os pedidos que "falharam" estavam gravados com a preferência
// do Mercado Pago criada.
const PAYMENT_PATH = /\/functions\/v1\/(store-create-payment|mp-create-payment)/;
const PAYMENT_TIMEOUT_MS = 45000;

// Without this, a request that never settles (dropped connection, a stuck
// proxy, a backgrounded tab resuming mid-request) leaves its promise pending
// forever — any page awaiting it gets stuck on its loading state until a hard
// reload. This guarantees every Supabase call either resolves or rejects.
// ── sessão morta no servidor ────────────────────────────────────────────────
// O access token vale pela ASSINATURA por até 1h, então quando a sessão deixa
// de existir do lado do servidor (limite de telas, encerramento em massa,
// conta apagada) o app continua renderizando como se estivesse tudo bem — e só
// as chamadas ao servidor voltam 401. Foi o que apareceu pro aluno como
// "Sessão inválida" dentro do player, sem nenhuma saída na tela.
//
// Detectar aqui, no único lugar por onde TODA chamada passa, encerra a sessão
// local na primeira recusa: o AuthContext assume e leva pro login.
//
// LISTA DE PERMITIDOS, não "qualquer 401". Estas funções são as que o aluno
// chama o tempo todo e que só devolvem 401 quando a SESSÃO não vale — é o
// sinal que interessa.
//
// A primeira versão derrubava em qualquer 401 e isso expulsou do painel quem
// abria o dashboard: `admin-capi-health` exige service role e responde 401
// para QUALQUER token de usuário, inclusive de admin. Ou seja, 401 também
// significa "esta chamada não é para você" — nada a ver com sessão morta.
//
// `member-auth-request` fica de fora de propósito: lá 401 é senha errada.
const SESSAO_PATH = /\/functions\/v1\/member-(lesson-token|stream-file|account-info|capture-location)/;
let encerrandoSessaoMorta = false;

function checarSessaoMorta(url: string, res: Response) {
  if (res.status !== 401 || !SESSAO_PATH.test(url) || encerrandoSessaoMorta) return;
  encerrandoSessaoMorta = true;
  // scope 'local': a sessão já não existe no servidor, pedir pra encerrar lá
  // só tomaria outro 401. Isso dispara SIGNED_OUT e o AuthContext explica.
  supabase.auth.signOut({ scope: 'local' })
    .catch(() => { /* o importante é o estado local ter sido limpo */ })
    .finally(() => { encerrandoSessaoMorta = false; });
}

function fetchWithTimeout(input: RequestInfo | URL, init: RequestInit = {}): Promise<Response> {
  const url = typeof input === 'string' ? input : input instanceof URL ? input.href : input.url;
  if (TIMEOUT_EXEMPT.test(url)) {
    return fetch(input, init).then(res => { checarSessaoMorta(url, res); return res; });
  }

  const timeoutMs = PAYMENT_PATH.test(url)
    ? PAYMENT_TIMEOUT_MS
    : AUTH_PATH.test(url) ? AUTH_TIMEOUT_MS : FETCH_TIMEOUT_MS;
  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), timeoutMs);
  if (init.signal) {
    if (init.signal.aborted) controller.abort();
    else init.signal.addEventListener('abort', () => controller.abort(), { once: true });
  }
  return fetch(input, { ...init, signal: controller.signal })
    .finally(() => clearTimeout(timeoutId))
    .then(res => { checarSessaoMorta(url, res); return res; });
}

// No custom `lock` here — this version of @supabase/auth-js dedupes
// concurrent refreshes itself and explicitly documents its own lock
// primitives as a legacy path kept only for backwards-compatible imports
// ("TODO(v3): remove legacy lock path", all over GoTrueClient). Supplying
// any custom lock function (this project previously had two: a no-op, then
// a hand-rolled FIFO queue) forces the client onto that legacy path instead
// of the modern lockless default — and neither hand-rolled version honored
// `acquireTimeout`, the internal budget GoTrueClient relies on to fail fast
// instead of blocking. That's what left users stuck on a loading spinner
// after login. Trust the library's own default.
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: createSafeStorage(),
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: fetchWithTimeout,
  },
});
